import {
  yourProfileImgLarge,
  yourProfileImgMedium,
  yourProfileImgSmall,
  pizzaMarketImgLarge,
  pizzaMarketImgMedium,
  pizzaMarketImgSmall,
  computerCourseImgLarge,
  computerCourseImgMedium,
  computerCourseImgSmall,
  safariImgLarge,
  safariImgMedium,
  safariImgSmall,
  uiLibImgLarge,
  uiLibImgMedium,
  uiLibImgSmall,
  reactContactsImgLarge,
  reactContactsImgMedium,
  reactContactsImgSmall,
} from "./projectImages";

const projectsData = [
  {
    name: "UI-Lib",
    href: "https://lubov-nefed.github.io/irina-nik-design-system",
    largeImg: uiLibImgLarge,
    mediumImg: uiLibImgMedium,
    smallImg: uiLibImgSmall,
    techs: ["React", "TS"],
  },
  {
    name: "React-Contacts",
    href: "https://lubov-nefed.github.io/irina-nik-design-system",
    largeImg: reactContactsImgLarge,
    mediumImg: reactContactsImgMedium,
    smallImg: reactContactsImgSmall,
    techs: ["React"],
  },
  {
    name: "Your Profile",
    href: "https://lubov-nefed.github.io/your-profile-react/",
    largeImg: yourProfileImgLarge,
    mediumImg: yourProfileImgMedium,
    smallImg: yourProfileImgSmall,
    techs: ["React"],
  },
  {
    name: "Pizza Market",
    href: "https://lubov-nefed.github.io/pizza-market/",
    largeImg: pizzaMarketImgLarge,
    mediumImg: pizzaMarketImgMedium,
    smallImg: pizzaMarketImgSmall,
    techs: ["JS"],
  },
  {
    name: "Computer Course",
    href: "https://lubov-nefed.github.io/computer-building-course/",
    largeImg: computerCourseImgLarge,
    mediumImg: computerCourseImgMedium,
    smallImg: computerCourseImgSmall,
    techs: ["JS"],
  },
  {
    name: "Safari",
    href: "https://lubov-nefed.github.io/safari-project/",
    largeImg: safariImgLarge,
    mediumImg: safariImgMedium,
    smallImg: safariImgSmall,
    techs: [""],
  },
];

export { projectsData };
